### ISSUE TITLE
Multiple TFT displays?

### ISSUE THREAD

**Issue by Andon-A** [notro/fbtft#132]
I've had a glance around the wiki and I haven't been able to find anything, which makes me think this isn't supported.

My concept is to run two of the Adafruit 2.2" displays (http://www.adafruit.com/products/1480) and hopefully build some form of clever "3d" view thing (Potentially with a camera for each screen). Does fbtft support multiple displays in this manner? The Pi certainly has the GPIO pins for it, but that doesn't mean the software will work.

**Comment by kunguz** [comment]
Is this currently possible in the existing version? Any pointer will be appreciated.

**Comment by notro** [comment]
It's still possible, there's no limit on the number of displays, but there is a limit on the number of busses available to connect displays to.
As stated, fbtft_device can only add one device, but using Device Tree it's easy to add devices.
If you use Raspberry Pi or BBB it's even easier since you can just create a Device Tree overlay.

**Comment by kunguz** [comment]
I used the device tree methodology already. Both displays are operational at the moment. Thank you.
