### ISSUE TITLE
adafruit18fb: "green tab" version has extra random pixels on two edges

### ISSUE THREAD

**Issue by notro** [notro/fbtft#2]
According to the work of Kamal Mostafa, set_addr_win() has to be modified.
See: https://github.com/kamalmostafa/raspberrypi-linux/blob/rpi-3.2.27%2Bkamal-st7735fb/drivers/video/st7735fb/st7735fb.c

When I get the time, I will modify the driver by adding support for 2 devices so it can handle both versions.

**Comment by sirdel** [comment]
Was working nicely up until I rotated by 90 deg :-
`sudo modprobe fbtft_device name=adafruit18_green rotate=90`
which causes the random pixels to appear.

Can be fixed by initialising without a rotation, removing the module and then inserting again with rotation :-
`sudo modprobe fbtft_device name=adafruit18_green`
`sudo modprobe -r  fbtft_device`
`sudo modprobe fbtft_device name=adafruit18_green rotate=90`
