### ISSUE TITLE
Greyscale pixel format and updating only a partial area to improve framerate (ili9341)

### ISSUE THREAD

**Issue by smlehbleh** [notro/fbtft#488]
Hello,
I've got a 16:9 video playing back on a 320 x 240 pitft(ili9341) using the fbdev library. Its getting around 19fps which is to be expected.

I was wondering does fbtft support partial updating of the screen? Because its a 16:9 video, theres black bars which are adding unecessary bytes to the transfer.

Also, does fbtft support greyscale format with the ili9341 to possibly triple the frame rate?

Cheers
Russell

**Comment by notro** [comment]
It's a long time since I've used or worked on fbtft, but maybe this pages can give some insight:
https://github.com/notro/fbtft/wiki/FPS
https://github.com/notro/fbtft/wiki/Performance

If you enable DEBUG_UPDATE_DISPLAY you'll get a line in the kernel log on each update that says which part was updated:
https://github.com/notro/fbtft/wiki/Debug
http://elixir.free-electrons.com/linux/latest/ident/fbtft_update_display

> greyscale

The ILI9341 supports RGB565, RGB666 and a reduce 8-bit color mode for power saving. I couldn't find anything about greyscale in the [datasheet](https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf).
