### ISSUE TITLE
Cannot enable debug messages

### ISSUE THREAD

**Issue by LordRafa** [notro/fbtft#537]
I am trying to enable the fbtft debug messages but I have not been able to do so.

My kernel has been compiled with the dynamic debug flag and I have executed these commands to try to enable the debug logs:
`echo 'module fbtft +p' > /sys/kernel/debug/dynamic_debug/control`
`echo 'module fbtft_device +p' > /sys/kernel/debug/dynamic_debug/control`
`echo 8 > /proc/sys/kernel/printk`

But when I insert de module with:
`sudo modprobe fbtft_device name=ra8876_800x600 gpios=reset:46,dc:7 busnum=2 debug=7`

I cannot see any debug message on the dmesg output.

**Comment by notro** [comment]
I haven't used fbtft in a long time so I don't know if something is broken, but ```debug=7``` should give you all fbtft debug messages. You don't need to enable debug printing since fbtft use dev_info():
[fbtft_par_dbg()](https://elixir.bootlin.com/linux/latest/ident/fbtft_par_dbg):
```c
#define fbtft_par_dbg(level, par, format, arg...)            \
do {                                                         \
	if (unlikely(par->debug & level))                    \
		dev_info(par->info->device, format, ##arg);  \
} while (0)

```
(The value ```debug=7``` gets expanded in [fbtft_expand_debug_value()](https://elixir.bootlin.com/linux/latest/ident/fbtft_expand_debug_value))

```/proc/sys/kernel/printk``` controls what gets printed to the console, not what goes into the kernel log (dmesg), so no need to set that.

Wait, you say you don't see any output, not from [fbtft_device](https://elixir.bootlin.com/linux/latest/source/drivers/staging/fbtft/fbtft_device.c) either? It should print the device it registers.
