### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by NickDG** [notro/fbtft#602]
Hi Notro,

I have a raspberry Pi 2GB and purchased the following screen https://www.amazon.de/-/en/dp/B08TCFDX8B?psc=1&ref=ppx_yo2ov_dt_b_product_details , thinking it would be easy to connect to the raspberry PI, I see its nothing easy. Iv wired up the Pi to the screen as mentioned in the Generic 7" screen running a ARM SSD1963, but not I'm lost, I'm not sure if I need to run a specific version of raspberry OS, and I'm confused on what to run to get this screen working. If you could assist it would be greatly appreciated.

**Comment by NickDG** [comment]
Technical data:
LCD Type: TFT Transmissive Normal WhiteInterface: 16-bit parallel bus interfaceCircuit board color: BlueModule size: 18 x 10.7 cm / 7.09 x 4.21 inches. Display size: 16.5 x 10 cm / 6.50 x 3.94 inches. Pixel spacing: 0.179mm x 0.179mm

7.0 inch TFT LCD module, resolution 800 x 480, SSD1963 controller, RA8875. The display module has an integrated 400 mA DC DC boost controller that can power the LCD backlight. an LCD-specific Initialization code so you can save time to optimise the power control register and gamma curve and achieve the best display performance. Display module standard 2 x 20 2.54 mm pin header, for connecting the MCU/development board. Please note. that the voltage is all data ports of the display module must not exceed 3.6 V.

the pins are wired up as follow 

3.3V |   | 5V | Can use 3.3V if R3 is shorted. See schematic
GND |   | GND | Ground
5V |   | 5V | Connect directly or with a apart source
LED | led | 3.3V | Can't drive backlight directly. Use transistor (50mA) or GPIO X
RS | dc | GPIO3 | GPIO1 rev 2
WR | wr | GPIO4 | GPIO2 rev 2
RD |   | 3.3V |  
DB0 | db00 | GPIO17 |  
DB1 | db01 | GPIO27 |  
DB2 | db02 | GPIO22 |  
DB3 | db03 | GPIO6 |  
DB4 | db04 | GPIO13 |  
DB5 | db05 | GPIO19 |  
DB6 | db06 | GPIO26 |  
DB7 | db07 | GPIO20 |  
DB8 | db08 | GPIO5 |  
DB9 | db09 | GPIO8 |  
DB10 | db10 | GPIO18 |  
DB11 | db11 | GPIO23 |  
DB12 | db12 | GPIO24 |  
DB13 | db13 | GPIO21 |  
DB14 | db14 | GPIO12 |  
DB15 | db15 | GPIO16 |  
CS | cs | GND | Ground
RST | reset | GPIO2

Touch

-- | -- | --
T_CLK | SCLK |  
T_DIN | MOSI |  
T_DOUT | MISO |  
T_CS | CE1 |  
T_IRQ | GPIO25 | Set default RB Jessie

**Comment by NickDG** [comment]
All i get when i turn on the Pi is a white screen nothing else

**Comment by notro** [comment]
You need a Device Tree overlay that describes the display. I haven't seen a working overlay for a parallel bus display. This is what I wrote in 2018: https://forums.raspberrypi.com/viewtopic.php?t=208264#p1288018

Here is someone that have at least looked at the problem for a SSD1963 #467 

Be aware that there has been some changes to gpio polarity handling in Linux v5.14: [staging: fbtft: Rectify GPIO handling](https://github.com/torvalds/linux/commit/ec03c2104365ead0a33627c05e685093eed3eaef)

**Comment by jamesc2151** [comment]
You code help me jump thru many hoops and directions but just want to post a Thanks and update of what I got working using Framebuffers and this might help you somehow..

Working with Raspberry 64bit last release before bookworm  I finally got an generic  ili9341 SPI tft display too correctly show me a booting console screen as it booted... still tweaking it but so far here is what I had to do

Etc\modules load --- spi_bcm2835
Config text.........
hdmi_group=2
hdmi_mode=4
hdmi_mode=4
hdmi_cvt 480 360 60 6 0 0 0
hdmi_drive=2
enable_uart=1
dtoverlay=fbtft,spi0-0,ili9341,reset_pin=24,dc_pin=25,led_pin=18,rotate=90

The overlay is already part of the OS i just had to find the right settting..
The display is https://www.amazon.com/dp/B09XHJ9KRX?ref=ppx_yo2ov_dt_b_product_details&th=1

I don't have the touch connected but will be playing with it latter on...  I did note that launching kodi from the tft gave me kodi output on the Primary HDMI and left the TFT showing background stats of errors it thows up while running so now I know why kodi freezes on me is because it's trying to reload MPD which I have running already..

Thanks for the info and keep on keep'n on
JC
