### ISSUE TITLE
Problem with SPI interface circuit

### ISSUE THREAD

**Issue by masoudr** [notro/fbtft#89]
Hi notro,
first I wanna say thank you for your great work.
I have a 2.4 inch tft lcd with ili9325 drive which worked fine with your kernel and 8bit parallel data bus,but I wanna use your spi interface circuit,but I can't get it work :(
I tried your test script and last night I got an error that was about "wr" pin,so I changed the "STR" pin which comes from 4096 to Q3 instead of Q2 in 4040 IC (as you mentioned in the circuit) so the problem with "wr" fixed.
but still I have nothing in my screen,even when I load the driver still I have only white screen(I know if I make it work it will go black with back light on)
So I couldnt get it worked yet,and I dont know what should I do.
can you help me ?
also I use these ICs in my circuit maybe the problem is there:
CD74HC4040
TC74HC4049AP
TC74HCU04AP
## thanks.

edit:
finally I get it working:
"sudo modprobe fbtft dma"
but I set the speed on 16 Mhz and I think it is too slow,but when I change it to 32Mhz,the Speed get better but the colors get worst :(

**Comment by stevstrong** [comment]
Sorry to wake up this thread here after such long inactivity time, but I would like to share my experience with the [SPI interface posted here](https://github.com/notro/fbtft/wiki/SPI-interface-circuit).

I am driving the [480x320 display board](https://www.aliexpress.com/item/Free-shipping-LCD-module-Pi-TFT-3-5-inch-320-480-Touchscreen-Display-Module-TFT-for/32551712173.html) with a [Blue Pill](http://wiki.stm32duino.com/index.php?title=Blue_Pill), and during my tests I encountered the problem of the display not working (corrupted colors) with frequencies higher than 24MHz (see [my detailed posts here](http://www.stm32duino.com/viewtopic.php?f=9&t=1654&start=90#p22204)).

I have found out that the bottleneck is the involved 74HC4040 counter - it has (on my board at least) a huge propagation delay (tPD~40ns) which brings the generated WR pulse out of sync relative to the shifted parallel data (16 bits) when using SPI at 36MHz.

The (partial) solution I have implemented is inserting additional delays to the MOSI and SCK signals. This I have implemented using the free inverter gates available in the on-board 74HC04 circuit.

The other part of the solution is to increase a bit the supply voltage (3.8V instead of 3.3V). This reduces the disturbing propagation delay of the 4040 counter.

Hope that I could help other users confronted with the same problem.
